// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPickleRandomHandlerFunc turns a function with the right signature into a get pickle random handler
type GetPickleRandomHandlerFunc func(GetPickleRandomParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPickleRandomHandlerFunc) Handle(params GetPickleRandomParams) middleware.Responder {
	return fn(params)
}

// GetPickleRandomHandler interface for that can handle valid get pickle random params
type GetPickleRandomHandler interface {
	Handle(GetPickleRandomParams) middleware.Responder
}

// NewGetPickleRandom creates a new http.Handler for the get pickle random operation
func NewGetPickleRandom(ctx *middleware.Context, handler GetPickleRandomHandler) *GetPickleRandom {
	return &GetPickleRandom{Context: ctx, Handler: handler}
}

/* GetPickleRandom swagger:route GET /pickle/random getPickleRandom

Return a random Pickle Image

*/
type GetPickleRandom struct {
	Context *middleware.Context
	Handler GetPickleRandomHandler
}

func (o *GetPickleRandom) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPickleRandomParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
