// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetPickleNameHandlerFunc turns a function with the right signature into a get pickle name handler
type GetPickleNameHandlerFunc func(GetPickleNameParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPickleNameHandlerFunc) Handle(params GetPickleNameParams) middleware.Responder {
	return fn(params)
}

// GetPickleNameHandler interface for that can handle valid get pickle name params
type GetPickleNameHandler interface {
	Handle(GetPickleNameParams) middleware.Responder
}

// NewGetPickleName creates a new http.Handler for the get pickle name operation
func NewGetPickleName(ctx *middleware.Context, handler GetPickleNameHandler) *GetPickleName {
	return &GetPickleName{Context: ctx, Handler: handler}
}

/* GetPickleName swagger:route GET /pickle/{name} getPickleName

Return the Pickle Rick Image.

*/
type GetPickleName struct {
	Context *middleware.Context
	Handler GetPickleNameHandler
}

func (o *GetPickleName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetPickleNameParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
