// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Pickle pickle
//
// swagger:model Pickle
type Pickle struct {

	// name
	// Example: my-pickle
	Name string `json:"name,omitempty"`

	// path
	// Example: my-pickle.png
	Path string `json:"path,omitempty"`

	// url
	// Example: https://raw.githubusercontent.com/cameracode/ricksofpickle/Develop/arakaki-picklerick.png
	URL string `json:"url,omitempty"`
}

// Validate validates this pickle
func (m *Pickle) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this pickle based on context it is used
func (m *Pickle) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Pickle) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Pickle) UnmarshalBinary(b []byte) error {
	var res Pickle
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
